name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update timestamp comment in frontend.py
        run: |
          sed -i '/# KEEP_ALIVE_TIMESTAMP/d' frontend.py
          echo "# KEEP_ALIVE_TIMESTAMP: $(date)" >> frontend.py

      - name: Commit and push changes using create-pull-request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: "Keep alive: timestamp update"
          title: "Keep alive commit"
          body: "Automated timestamp update to keep the Streamlit app alive."
          base: main
          push-to-fork: false
          delete-branch: true
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
