name: Keep Streamlit App Alive
on:
  schedule:
    - cron: '0 */12 * * *'          
  workflow_dispatch:

permissions:                        
  contents: write

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4    

      - name: Update timestamp comment
        run: |
          sed -i '/# KEEP_ALIVE_TIMESTAMP/d' frontend.py
          echo "# KEEP_ALIVE_TIMESTAMP: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> frontend.py

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # stage the change (there will always be one – the new timestamp)
          git add frontend.py

          # if nothing changed, exit quietly so the job is green
          git diff --cached --quiet && { echo "No changes"; exit 0; }

          git commit -m "chore: keep-alive $(date -u +"%Y-%m-%dT%H:%M:%SZ")"

          # push straight to main
          git push origin HEAD:main
